name: xq_i18n
description: A new Flutter project to secondary packaging based on "i18n_extension".
version: 0.0.1
homepage: 'https://github.com/xq-life/xq_i18n'

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # dio https://pub.flutter-io.cn/packages/dio
  dio: 4.0.6

  # i18n_extension https://pub.flutter-io.cn/packages/i18n_extension
  i18n_extension: 4.2.1

  # path_provider https://pub.flutter-io.cn/packages/path_provider
  path_provider: 2.0.9

  # permission_handler https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: 9.2.0

  # sp_util https://pub.flutter-io.cn/packages/sp_util
  sp_util: 2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
